import type { InboxNotification } from "./types"

export const DEMO_INBOX_NOTIFICATIONS: readonly InboxNotification[] = [
  {
    id: "demo-101",
    unread: true,
    reason: "review_requested",
    updatedAt: "2026-09-08T12:15:00Z",
    lastReadAt: null,
    title: "Evitar corrida na atualização automática",
    subjectType: "PullRequest",
    subjectState: "open",
    repository: "equipe/api",
    repositoryUrl: "https://github.com/equipe/api",
    subjectApiUrl: "https://api.github.com/repos/equipe/api/pulls/142",
    threadApiUrl: "https://api.github.com/notifications/threads/101",
    subscriptionApiUrl: "https://api.github.com/notifications/threads/101/subscription",
    url: "https://github.com/equipe/api/pull/142",
  },
  {
    id: "demo-102",
    unread: true,
    reason: "mention",
    updatedAt: "2026-09-08T10:40:00Z",
    lastReadAt: null,
    title: "Loader cobre a última linha da lista",
    subjectType: "Issue",
    subjectState: "open",
    repository: "equipe/web",
    repositoryUrl: "https://github.com/equipe/web",
    subjectApiUrl: "https://api.github.com/repos/equipe/web/issues/204",
    threadApiUrl: "https://api.github.com/notifications/threads/102",
    subscriptionApiUrl: "https://api.github.com/notifications/threads/102/subscription",
    url: "https://github.com/equipe/web/issues/204",
  },
  {
    id: "demo-103",
    unread: false,
    reason: "assign",
    updatedAt: "2026-09-07T18:05:00Z",
    lastReadAt: "2026-09-08T08:00:00Z",
    title: "Documentar atalhos do Inbox",
    subjectType: "Issue",
    subjectState: "closed",
    repository: "equipe/docs",
    repositoryUrl: "https://github.com/equipe/docs",
    subjectApiUrl: "https://api.github.com/repos/equipe/docs/issues/77",
    threadApiUrl: "https://api.github.com/notifications/threads/103",
    subscriptionApiUrl: "https://api.github.com/notifications/threads/103/subscription",
    url: "https://github.com/equipe/docs/issues/77",
  },
]
